CREATE TABLE Invoices (
    InvoiceId UNIQUEIDENTIFIER PRIMARY KEY,
    InvoiceNo BIGINT IDENTITY(1,1) UNIQUE NOT NULL,
    CustomerName NVARCHAR(255) NOT NULL,
    InvoiceDate DATETIME NOT NULL,
    DiscountPercent DECIMAL(5,2) NOT NULL DEFAULT 0,
    TaxPercent DECIMAL(5,2) NOT NULL DEFAULT 0
);

CREATE TABLE InvoiceItems (
    InvoiceItemId UNIQUEIDENTIFIER PRIMARY KEY,
    InvoiceId UNIQUEIDENTIFIER NOT NULL
        FOREIGN KEY REFERENCES Invoices(InvoiceId) ON DELETE CASCADE,
    Description NVARCHAR(255) NOT NULL,
    Quantity INT NOT NULL,
    UnitPrice DECIMAL(18, 2) NOT NULL
);