name: CD - All Tests

on:
  pull_request:
    branches:
      - production

jobs:
  test-and-deploy:
    runs-on: windows-latest

    services:
      sql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: "Your_password123"
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
        options: >-
          --health-cmd "exit 0"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore packages
      run: nuget restore LiteBiller.sln

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build solution
      run: msbuild LiteBiller.sln /p:Configuration=Release

    - name: Wait for SQL Server to be ready
      shell: pwsh
      run: |
        Write-Host "Waiting for SQL Server to be ready..."
        Start-Sleep -Seconds 15

    - name: Create LiteBiller database
      run: |
        sqlcmd -S localhost -U sa -P Your_password123 -Q "CREATE DATABASE LiteBiller"

    - name: Override app.config for CD (Docker connection)
      run: copy LiteBiller.Tests\app-cd-docker.config LiteBiller.Tests\app.config
      shell: cmd

    - name: Run setup script to create tables
      run: |
        sqlcmd -S localhost -U sa -P Your_password123 -d LiteBiller -i LiteBiller.Tests\sql\setup.sql

    - name: Run all tests (Unit + Integration)
      shell: pwsh
      run: |
        & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" `
        LiteBiller.Tests\bin\Release\LiteBiller.Tests.dll