- name: Locate vstest.console.exe
  shell: pwsh
  run: |
    $vstestPath = Get-ChildItem -Path "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2022" -Recurse -Filter vstest.console.exe -ErrorAction SilentlyContinue | Select-Object -First 1
    Write-Host "vstest.console.exe found at: $($vstestPath.FullName)"